import streamlit as st
import requests
from PyPDF2 import PdfReader
from docx import Document
import io

# Backend API URL
API_URL = "http://127.0.0.1:8000/evaluate_candidate"

# Page config
st.set_page_config(page_title="HR Resume Matcher", page_icon="📝", layout="wide")

st.title("🤖 AI Resume Matcher & Feedback Generator")
st.markdown("**ML-powered resume screening + GenAI personalized emails. Supports PDF/Word uploads!**")

# Sidebar for instructions
with st.sidebar:
    st.header("🚀 Quick Start")
    st.info("""
    1. Upload/Paste Job Description
    2. Enter Candidate Name
    3. Upload PDF/Word or Paste Resume
    4. Click **Evaluate** → Get score + email!
    """)
    st.header("🔧 Status")
    st.success("✅ Backend running at http://127.0.0.1:8000")

# Inputs
col1, col2 = st.columns(2)

with col1:
    st.header("📋 Job Description")
    jd_file = st.file_uploader("Upload JD (TXT/PDF)", type=['txt', 'pdf'], key="jd")
    if jd_file:
        if jd_file.type == "application/pdf":
            jd_text = ""
            reader = PdfReader(io.BytesIO(jd_file.read()))
            for page in reader.pages:
                jd_text += page.extract_text()
        else:
            jd_text = jd_file.read().decode('utf-8')
        st.text_area("JD Preview:", value=jd_text[:500] + "..." if len(jd_text) > 500 else jd_text, height=200)
    else:
        jd_text = st.text_area("Paste Job Description...", height=300)

with col2:
    st.header("👤 Candidate")
    candidate_name = st.text_input("Full Name *")
    
    st.subheader("📄 Resume")
    resume_file = st.file_uploader("Upload Resume (PDF/Word/DOCX)", type=['pdf', 'docx'], key="resume")
    
    if resume_file:
        if resume_file.type == "application/pdf":
            resume_text = ""
            reader = PdfReader(io.BytesIO(resume_file.read()))
            for page in reader.pages:
                resume_text += page.extract_text()
        elif resume_file.type == "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
            doc = Document(io.BytesIO(resume_file.read()))
            resume_text = "\\n".join([para.text for para in doc.paragraphs])
        st.text_area("Resume Preview:", value=resume_text[:500] + "..." if len(resume_text) > 500 else resume_text, height=200)
    else:
        resume_text = st.text_area("Or Paste Resume Text...", height=250)

# Evaluate button
if st.button("🚀 Evaluate Candidate", type="primary", use_container_width=True):
    if not all([candidate_name, jd_text, resume_text]):
        st.error("❌ Fill all fields!")
    else:
        with st.spinner("🔬 Analyzing with ML + GenAI..."):
            try:
                response = requests.post(API_URL, data={
                    "candidate_name": candidate_name,
                    "resume_text": resume_text,
                    "jd_text": jd_text
                })
                if response.status_code == 200:
                    data = response.json()
                    score = data['match_score']
                    
                    # Results
                    st.divider()
                    st.header(f"✅ Results for {data['candidate_name']}")
                    
                    col_score, col_status = st.columns([1, 3])
                    with col_score:
                        st.metric("Similarity Score", f"{score}%")
                        if score >= 70:
                            st.success("🎉 Shortlist!")
                        else:
                            st.warning("📋 Improve skills")
                    st.progress(min(score / 100, 1.0))
                    
                    st.subheader("✉️ Auto-Generated Feedback Email")
                    st.text_area(
                        label="Copy & Send",
                        value=data['feedback_email'],
                        height=350,
                        help="Ready-to-send personalized email generated by Gemini AI"
                    )
                else:
                    st.error(f"API Error: {response.text}")
            except Exception as e:
                st.error(f"Connection error: {e}")

st.markdown("---")
st.caption("💡 Powered by TF-IDF ML + Google Gemini. Backend auto-reloads.")

